backend:
  name: github
  repo: uri500/op-soluciones-web
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Categoría", name: "categoria", widget: "select", options: ["Mantenimiento", "Ingeniería marítima", "Consultoría", "Tecnología"] }
      - { label: "Resumen", name: "excerpt", widget: "text" }
      - { label: "Contenido", name: "body", widget: "markdown" }
